version: '3'

services:
  whisper:
    build:
      context: ./whisper
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
      - ./models:/models
    ports:
      - "${PORT:-9999}:80"
    environment:
      - MODEL_SIZE=${MODEL_SIZE:-medium}
      - LANGUAGE=${LANGUAGE:-ja}
    restart: unless-stopped
    # 初期化スクリプトを実行
    entrypoint: >
      bash -c "
        mkdir -p /data/uploads /data/processed /data/exports /data/logs /data/config &&
        chown -R www-data:www-data /data /models &&
        apache2-foreground
      "

volumes:
  models: