version: '3'

services:
  whisper:
    build:
      context: ./whisper
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
      - ./src:/var/www/html  # srcディレクトリをウェブルートにマウント
    ports:
      - "${PORT:-9999}:80"
    environment:
      - MODEL_SIZE=${MODEL_SIZE:-base}
      - LANGUAGE=${LANGUAGE:-ja}
      - APP_NAME=SHOKI
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL=${GEMINI_MODEL:-gemini-1.5-pro}
    restart: unless-stopped
    entrypoint: >
      bash -c "
        mkdir -p /data/uploads /data/processed /data/exports /data/logs /data/config /data/cache /data/archives &&
        chown -R www-data:www-data /data /var/www/html &&
        chmod -R 775 /data /var/www/html &&
        /usr/local/bin/docker-entrypoint.sh
      "

volumes:
  data: