version: '3'

services:
  whisper:
    build:
      context: ./whisper
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
      - ./models:/models
    ports:
      - "${PORT:-9999}:80"
    environment:
      - MODEL_SIZE=${MODEL_SIZE:-medium}
      - LANGUAGE=${LANGUAGE:-ja}
      - APP_NAME=SHOKI
    restart: unless-stopped
    entrypoint: >
      bash -c "
        mkdir -p /data/uploads /data/processed /data/exports /data/logs /data/config /data/cache /data/archives &&
        chown -R www-data:www-data /data /models &&
        chmod -R 775 /data /models &&
        /usr/local/bin/docker-entrypoint.sh
      "

volumes:
  models: